[phases.setup]
nixPkgs = ["nodejs", "python310"]

[phases.install]
cmds = [
  "npm install",
  "python3.10 -m venv .venv",
  "source .venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && npm run start"
